### ISSUE TITLE
Data from Unix/Linux platforms is tagged as 'junos'

### ISSUE THREAD

**Issue by nathancatania** [napalm-automation/napalm-logs#197]
When sending data from rsyslog on a Linux server to napalm-logs, the messages corresponding to the server are being tagged as `'os': 'junos'`, instead of `'os':'unknown'` (given no default parser for syslog data sent from servers).

The syslog messages from both a Junos device and a server have the same format (I am assuming due to Junos being based on FreeBSD):

Example Junos:
```
Nov 20 08:48:52  vmx1 sshd[43934]: Accepted publickey for username from AAA.BBB.CCC.DDD port 49446 ssh2: RSA SHA256:XXXXXXXXXX
```

Example Ubuntu Server:
```
Nov 20 07:52:59 server1 sshd[685]: Accepted publickey for username from AAA.BBB.CCC.DDD port 64846 ssh2: RSA SHA256:XXXXXXXXXX
Nov 20 07:52:59 server1 systemd-logind[1197]: New session 177 of user username.
```

Example dump (of server syslog) from Kafka:
```
{'message_details': {'processId': '3011', 'severity': 6, 'facility': 4, 'hostPrefix': None, 'pri': '38', 'host': 'server1', 'tag': 'sshd', 'time': '09:16:59', 'date': 'Nov 20', 'message': 'Accepted publickey for username from AAA.BBB.CCC.DDD port 64846 ssh2: RSA SHA256:XXXXXXXXXX'}, 'timestamp': 1511169419, 'facility': 4, 'ip': 'WWW.XXX.YYY.ZZZ', 'host': 'server1', 'error': 'RAW', 'os': 'junos', 'model_name': 'raw', 'severity': 6}
```
As it stands, under the above circumstances, the data coming in for some devices (ie: servers) is categorized incorrectly.

Possible solutions:
- Leave as is and filter by hostname on the application side (my current solution - doesn't address the issue).
- Write a parser for Unix/Linux devices (difficult due to the syslog formatting being identical).
- Change the OS tag for Junos to something more general, eg: "unix" (not ideal).
- Deploy two instances of napalm-logs: one as a Junos collector, one as a Unix collector; altering the Junos parser of the second instance to reflect `"os":"unix"` (not ideal).
- ?

**Comment by mirceaulinic** [comment]
Hi @nathancatania - thanks for your thoughts.

That's a very good point, and somehow I am pleasantly surprised that Junos (for once) doesn't manipulate the logs from the underlying operating system. Indeed, some messages come from the core daemons like `sshd`, `ntpd` etc.

As you mentioned, it would be very hard to distinguish between messages coming from the base operating system and other Unix systems. I would suggest a mixture of what you proposed:

- First off: it would be cleaner and more efficient to keep the network logs and system logs separately. For Kafka in particular, you could use different topics, e.g., `syslog.net` for the logs from network devices, and `syslog.srv` for servers etc.
- At the same time I would like to have a Unix profile, and I understand that would be pretty straightforward -- and with every message added for Junos, we cover the Unix one too (for those coming from the underlying daemons).
- Start two `napalm-logs` instances: one for network devices, one for servers, and to make it more efficient use the [`device_whitelist`](http://napalm-logs.readthedocs.io/en/latest/options/index.html#configuration-options-device-whitelist) and [`device_blacklist`](http://napalm-logs.readthedocs.io/en/latest/options/index.html#configuration-options-device-whitelist) configuration options, e.g.:

`/etc/napalm/logs/net_config`:
```yaml
device_blacklist:
  - unix
```

`/etc/napalm/logs/srv_config`:
```yaml
device_whitelist:
  - unix
```

This way it will be optimised to start only the processes for the platforms you target. But it requires the previous two items solved (`unix` profile added, and separate topics in Kafka).

- We can add `hostname_whitelist` and `hostname_blacklist` options too.

**Comment by nathancatania** [comment]
Thanks for the reply. My sentiments exactly regarding Junos' (lack of) manipulation of the underlying system logs.

I hadn't considered using the `device_blacklist` or `device_whitelist` configuration options and assumed I would have to modify the existing parsers in the second instance (great idea, thanks!).

I think I will transition from checking the hostname on the application side, to separating the network and server logs into different topics as per your recommendation above. The overhead of Napalm-logs seems to be minimal in my (limited) testing so the net system effect of running a second service for now should be small.

**Comment by mirceaulinic** [comment]
Hi @nathancatania - for the time being I will close this issues. Should you have more questions in this regard, don't hesitate to reopen.
Additionally, we can equally add two options `hostname_whitelist` and `hostname_blacklist` as previously mentioned as they might be handy. If you want, don't hesitate to submit a PR to review / discuss. Thanks!
