### ISSUE TITLE
Tests failing due to timestamp incorrect after new year

### ISSUE THREAD

**Issue by loverend** [napalm-automation/napalm-logs#204]
We have many tests which are failing due to the timestamp being incorrect:

```
E         -  u'timestamp': 1490713710,
E         ?                   ----
E         +  u'timestamp': 1522249710,
E         ?                 ++++
```

The reason for this is that most syslog messages do not contain the year.

Currently if the message that we receive does not contain the year we assume that it is from the current year. This will only really cause an issue (other than the failing tests) when we are changing years; if a log is generated at 23:59:59 on 31st dec and received a second later than the timestamp will be almost a year out.

Maybe we should exclude the timestamp from the tests.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-logs/commit/ff2ff1daf42a6e4a4ce65b5b28242e1cfa758e0c
