### ISSUE TITLE
Napalm logs

### ISSUE THREAD

**Issue by chella2830** [napalm-automation/napalm-logs#209]
Hello,
I am seeing that on my NX-OS - 
show logg

Logging server:                 enabled
{172.17.6.249}
However how do i see if syslogs are being sent to napalm?

**Comment by loverend** [comment]
Hi,

You can see exactly what is hitting napalm-logs by running `cli.py` with the flags `--log-file cli -l debug`:

http://napalm-logs.readthedocs.io/en/latest/options/index.html?#log-file
http://napalm-logs.readthedocs.io/en/latest/options/index.html?#log-level-warning

**Comment by mirceaulinic** [comment]
I am going to close this issue. @chella2830 if you still have any questions, please feel free to re-open.
