### ISSUE TITLE
Bug in coercing date to syslog time

### ISSUE THREAD

**Issue by lampwins** [napalm-automation/napalm-logs#255]
I found a fun little bug today with the way we are coercing the current year to the date of a syslog. I discovered that I have a device out there with an incorrect local time. The device believes it is February 29th and because the message does not contain the year, napalm-logs appends the current year from the napalm-logs server, which in this case is 2018. However, February 29, 2018 is not a valid date. This causes a `ValueError` to be thrown on the creation of the `datetime` object, stating as much.

The offending line is https://github.com/napalm-automation/napalm-logs/blob/master/napalm_logs/device.py#L218 which results in this traceback on server crash:

```
napalm_logs_1  | Traceback (most recent call last):
napalm_logs_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
napalm_logs_1  |     self.run()
napalm_logs_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
napalm_logs_1  |     self._target(*self._args, **self._kwargs)
napalm_logs_1  |   File "/usr/local/lib/python3.6/site-packages/napalm_logs/device.py", line 280, in start
napalm_logs_1  |     prefix_id)
napalm_logs_1  |   File "/usr/local/lib/python3.6/site-packages/napalm_logs/device.py", line 227, in _format_time
napalm_logs_1  |     parsed_time = datetime.strptime('{} {} {}'.format(year, date, time), '%Y {}'.format(time_format))
napalm_logs_1  |   File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
napalm_logs_1  |     tt, fraction = _strptime(data_string, format)
napalm_logs_1  |   File "/usr/local/lib/python3.6/_strptime.py", line 528, in _strptime
napalm_logs_1  |     datetime_date(year, 1, 1).toordinal() + 1
napalm_logs_1  | ValueError: day is out of range for month
```

The simple solution is to keep the current flow in place but use a try/catch to handle this case. What I am not sure of yet, is what to do when the exception is thrown? I think it would be reasonable to then fall back to the current date of the napalm-logs server and state this in an info log and in the docs.

**Comment by loverend** [comment]
This is indeed a fun bug. I think your suggestion of catching the exception and using current date in napalm-logs is an acceptable solution.
