### ISSUE TITLE
napalm logs don't show on salt events

### ISSUE THREAD

**Issue by basondole** [napalm-automation/napalm-logs#340]
Hello

Im trying to integrate napalm logs with salt with below configuration

```
$ napalm-logs --version
napalm-logs 0.9.0

$ cat /etc/napalm/logs
address: 0.0.0.0
port: 514
publisher: cli
disable_security: true
```

```
$ salt --version
salt 3001

$ cat /etc/salt/master
engines:
  - napalm_syslog:
      disable_security: true
      transport: cli
```

After running napalm-logs as `$ napalm-logs -c /etc/napalm/logs` I can see the incoming syslog messages from my junos network device but the syslog messages do not show in the event bus when viewing with `salt-run state.event pretty=True` also I can execute salt commands on the junos device without a problem.

Kindly assist with advice on what to check, or if any other output is required please let me know.

Thank you.

**Comment by mirceaulinic** [comment]
Hey @basondole - is napalm-logs running on the same machine as your Salt Master?

**Comment by basondole** [comment]
Yes. It does

>

**Comment by mirceaulinic** [comment]
You have `publisher: cli` configured on napalm-logs. In order to have napalm-logs and Salt communicate, you need to use a transport mechanism other than CLI (e.g., ZMQ, Kafka, etc.).
