### ISSUE TITLE
BUG: napalm-logs don't show syslog messages

### ISSUE THREAD

**Issue by khireddine10** [napalm-automation/napalm-logs#341]
I am trying to use napalm-logs tool, in my network, so when a problem occur in network device will sends the syslog message to napalm-logs server.

I've configured the cisco router to forward the syslog messages to my (napalm-logs) server using those commands.

_**cisco logging configuration**_
![image](https://user-images.githubusercontent.com/44124081/91096730-6ab45300-e656-11ea-8a6d-79472861dde3.png)

i'am using centos 7.

i've installed napalm-logs using pip2.7
![image](https://user-images.githubusercontent.com/44124081/91097230-3ab97f80-e657-11ea-87db-16e04045b60e.png)

**Example:**
when i shutdown the interface the cisco router sends syslog message normally to the sever
![image](https://user-images.githubusercontent.com/44124081/91097452-984dcc00-e657-11ea-98fd-fe2134f82f23.png)

wireshark output
![image](https://user-images.githubusercontent.com/44124081/91097485-ae5b8c80-e657-11ea-9a60-540ade4ead86.png)

centos firewall
![image](https://user-images.githubusercontent.com/44124081/91097575-dc40d100-e657-11ea-945e-167aaccded78.png)

receive syslog messages from other syslog tool (rsyslog)
![image](https://user-images.githubusercontent.com/44124081/91098430-5b82d480-e659-11ea-86e5-9c994a408ec1.png)

from the above, so the syslog are sends and receive normally

**The problem I am facing is:**
when i run the napalm-logs the tool does not show syslog messages.
![image](https://user-images.githubusercontent.com/44124081/91097912-7143ca00-e658-11ea-96c5-d55c2db05c15.png)

when i press ctrl+c i get this error
![image](https://user-images.githubusercontent.com/44124081/91098329-2d9d9000-e659-11ea-9c7f-2ffd43b77f47.png)

**Comment by khireddine10** [comment]
@mirceaulinic

**Comment by mirceaulinic** [comment]
Yes, you don't need to Ctr-C, napalm-logs is supposed to be running forever (e.g., managed by systemd or another service manager).

**Comment by khireddine10** [comment]
no, the napalm-log does not show any syslog message, but when terminate the proccess by using (ctrl-c)  i got this message.
![image](https://user-images.githubusercontent.com/44124081/97111997-2db21e80-16e2-11eb-83f0-215e6628a2f3.png)


in my project i've using beacons to monitor the interfaces but i am really steel want how to resolve this problem .
thanks for your response
