### ISSUE TITLE
Optional security

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-logs#43]
Make security optional - there are cases when people would only need to send the data as-is to a log server, i.e. logstash etc. In that case, security is a bit overkill.
Ping @loverend - what do you think?

**Comment by loverend** [comment]
I agree, it would also be useful for debugging too. It should be clear that there is no security though. Maybe even have the client explicitly request no security.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-logs/pull/51
