### ISSUE TITLE
Have 1 white space match 1+ white spaces in syslog message

### ISSUE THREAD

**Issue by loverend** [napalm-automation/napalm-logs#65]
Currently we look at the defined message in the config and take a white space to be exactly 1 white space. We should change it so 1 white space will match 1+ white spaces in the actual message.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-logs/commit/8ad179b068d8331d8e443b4b3f88bef3f824b3c3
